### ISSUE TITLE
Fails to start under NSight Graphics on Linux

### ISSUE THREAD

**Issue by dm-tesla** [NVIDIAGameWorks/RTXDI#11]
Using the latest NSight to date: 2022.4.1.0
Pointing it to either `rtxdi-sample` or `minimal-sample` - fails in either case.
NSight writes to the console:
```
terminate called after throwing an instance of 'vk::DeviceLostError'
  what():  vk::Device::waitIdle: ErrorDeviceLost
```
Error list:
```
ID,,Origin,Source,Message
1,,Target,NVIDIA Nsight Graphics,Graphics interception initialized
2,,Target,NVIDIA Nsight Graphics,"Adding VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT to buffer with device address usage. This can be disabled via ""Vulkan > Device Address C++ Support"""
3,,Target,NVIDIA Nsight Graphics,"Adding VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT to memory allocation with device address support. This can be disabled via ""Vulkan > Device Address C++ Support"""
```

**Comment by sawillms** [comment]
Thank you for the bug report and apologies for the inconvenience. This has been tested and found working with the [RTXDI v2.2.0 release](https://github.com/NVIDIAGameWorks/RTXDI/releases/tag/v2.2.0) and [Nsight Graphics 2024.1.1.0](https://developer.nvidia.com/nsight-graphics/get-started#latest) including frame capture and C++ project generation (after installing libxcb-icccm4-dev). Please let us know if there are further issues.
