### ISSUE TITLE
Unbiased + Fused Spatiotemporal combination has rendering artifacts

### ISSUE THREAD

**Issue by pablode** [NVIDIAGameWorks/RTXDI#19]
When combining both options in the RTXDI sample application, following artifacts can be observed:
<img width="961" alt="2023-06-19 16_46_11-RTX Direct Illumination SDK Sample (D3D12)" src="https://github.com/NVIDIAGameWorks/RTXDI/assets/3663466/f93c47f0-1d33-4b54-9983-8598faeee10a">
<img width="961" alt="2023-06-19 16_43_52-RTX Direct Illumination SDK Sample (D3D12)" src="https://github.com/NVIDIAGameWorks/RTXDI/assets/3663466/6c327e97-93c6-4998-b8c6-422223dd0535">
latest revision, RTX 2070

**Comment by sawillms** [comment]
Thank you for reporting this visual regression. This was fixed in the [v2.2.0 release](https://github.com/NVIDIAGameWorks/RTXDI/releases/tag/v2.2.0).
