### ISSUE TITLE
Run update_dependencies.bat, packman error 403 

### ISSUE THREAD

**Issue by shirokumaqwq** [NVIDIAGameWorks/RTXDI#25]
Hello
I tried to run the latest version.

Processing project file 'packman\dependencies.xml'
Package 'rtxdi-media' at version 'p4sw-30874147' is missing from local storage.
packman(ERROR): Unable to download file from 'https://d4i3qtqj3r0z5.cloudfront.net/rtxdi-media%40p4sw-30874147' (server returned 403)

Thank you

**Comment by holyodin776** [comment]
same here

**Comment by sawillms** [comment]
Hopefully the ["hotfix"](https://github.com/NVIDIAGameWorks/RTXDI/commit/73d62e18dc3653f6855af3686d22d78b115ece10) in January unblocked you, but we've decided to move away from Packman entirely with the [v2.2.0 release ](https://github.com/NVIDIAGameWorks/RTXDI/releases/tag/v2.2.0). Please try it out.
