### ISSUE TITLE
shaderCompiler multi threading deadlock issue

### ISSUE THREAD

**Issue by whitemousegary** [NVIDIAGameWorks/RTXDI#3]
I updated Window SDK to 19041, updated Visual Studio 2019 to the latest version and updated all _Windows SDK Version_ project setting to 10.0.19041.0.  Almost all projects could be compiled successfully, except the projects that would trigger/require shader compilation. After a bit of debugging, I found that the problem came from the program shaderCompiler.exe.  

When shaderCompiler.exe begins, the process will stop responding.  No error, no progress, indefinitely.  The following is the most that shaderCompiler.exe reports before it stops responding.
> Build started...
> 1>------ Build started: Project: rtxdi-sample-shaders, Configuration: Release x64 ------
> 1>[  2.2%] DXIL  OK   FusedResamplingPass.hlsl: USE_RAY_QUERY=0 RTXDI_REGIR_MODE=RTXDI_REGIR_DISABLED

I suspect it is a multi threading deadlock issue in the program shaderCompiler.exe.

Please help.  Thanks.

**Comment by sawillms** [comment]
Closing issue as I suspect this has long since been resolved but please do (re)open if it wasn't and it persists with latest sources.
