### ISSUE TITLE
cmake generator fails 

### ISSUE THREAD

**Issue by OptimisticMonkey** [NVIDIAGameWorks/RTXDI#7]
I have vulkan disabled, but it still tries to generate it 
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan: Found unsuitable version "", but required is at
  least "1.2.170" (found Vulkan_LIBRARY-NOTFOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindVulkan.cmake:159 (find_package_handle_standard_args)
  RTXGI/rtxgi-sdk/FindSDKs.cmake:38 (find_package)
  RTXGI/rtxgi-sdk/CMakeLists.txt:38 (include)

CMakeLists.txt:38  

option(DONUT_WITH_VULKAN "" OFF)

**Comment by apanteleev** [comment]
Please update to the latest version of the code, update the RTXGI submodule and try again.
The issue should've been fixed in 1bf7b7e54e58eb7fa399ca9d8d90af35d5a74d9f
