### ISSUE TITLE
error in configure process

### ISSUE THREAD

**Issue by A100KA** [NVIDIAGameWorks/RTXDI#8]
hello i have this error 
CMake Error at CMakeLists.txt:62 (add_subdirectory):
  The source directory

    C:/RTXDI-main/donut

  does not contain a CMakeLists.txt file.

CMake Error at shaders/CMakeLists.txt:2 (include):
  include could not find requested file:

    C:/RTXDI-main/donut/compileshaders.cmake

CMake Error at minimal/shaders/CMakeLists.txt:2 (include):
  include could not find requested file:

    C:/RTXDI-main/donut/compileshaders.cmake

**Comment by pierremoreau** [comment]
You most likely need to run `git submodule update --init --recursive` to fetch the different submodules. See [the instructions](https://github.com/NVIDIAGameWorks/RTXDI#windows) from the README.
